/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error": "#690005",
        "on-primary-fixed-variant": "#5c21a9",
        "surface-tint": "#d6baff",
        "on-secondary-fixed": "#001946",
        "surface-dim": "#131313",
        "tertiary-fixed": "#efdbff",
        "inverse-surface": "#e5e2e1",
        "on-tertiary-container": "#c185ff",
        "inverse-on-surface": "#313030",
        "on-primary-fixed": "#280056",
        "on-secondary-fixed-variant": "#00419e",
        "tertiary-fixed-dim": "#dcb8ff",
        "on-primary": "#430088",
        "on-primary-container": "#b889ff",
        "on-tertiary-fixed": "#2c0051",
        "surface-bright": "#393939",
        "on-surface": "#e5e2e1",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#ecdcff",
        "background": "#131313",
        "error-container": "#93000a",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-high": "#2a2a2a",
        "on-tertiary-fixed-variant": "#6700b5",
        "secondary-fixed-dim": "#b1c5ff",
        "outline": "#968d9e",
        "secondary-fixed": "#dae2ff",
        "surface-container": "#20201f",
        "secondary-container": "#0060e3",
        "on-secondary": "#002c71",
        "primary-container": "#4c0099",
        "on-surface-variant": "#cdc3d5",
        "inverse-primary": "#753fc2",
        "primary": "#d6baff",
        "surface-container-low": "#1c1b1b",
        "on-tertiary": "#480081",
        "tertiary-container": "#520091",
        "surface": "#131313",
        "primary-fixed-dim": "#d6baff",
        "on-background": "#e5e2e1",
        "on-secondary-container": "#e2e7ff",
        "secondary": "#b1c5ff",
        "outline-variant": "#4b4453",
        "error": "#ffb4ab",
        "surface-variant": "#353535",
        "surface-container-highest": "#353535",
        "tertiary": "#dcb8ff"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem", 
        "lg": "0.25rem", 
        "xl": "0.5rem", 
        "full": "0.75rem"
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}